In [27]:
import torch
import pandas as pd
import numpy as np
import math
import seaborn as sb
import matplotlib.pyplot as plt
import re

In [28]:
data1 = pd.read_csv("podaci_brisanje_i_sredjivanje_N.csv")

In [29]:
data1.head()

,Unnamed: 0,DateTime,T,P,U,DD,Ff,Nh,H,VV,sss
0,0,2012-09-26 08:00,21.0,1013.9,3,Wind blowing from the west-southwest,NaN,0,NaN,NaN,0.0
1,1,2012-09-26 09:00,24.0,1013.9,4,Wind blowing from the south-southwest,NaN,0,NaN,NaN,0.0
2,2,2012-09-26 10:00,26.0,1013.9,4,Wind blowing from the south-southwest,NaN,0,NaN,NaN,0.0
3,3,2012-09-26 11:00,28.0,1013.9,3,Wind blowing from the south-west,NaN,0,NaN,NaN,0.0
4,4,2012-09-26 12:00,29.0,1013.9,4,Wind blowing from the south,NaN,0,NaN,NaN,0.0

In [30]:
def encode_and_bind(original_dataframe, feature_to_encode):
    dummies = pd.get_dummies(original_dataframe[[feature_to_encode]])
    res = pd.concat([original_dataframe, dummies], axis=1)
    
    del res[feature_to_encode]
    
    return(res)

In [31]:
data2 = encode_and_bind(data1, "DD")

In [32]:
data2.head()

,Unnamed: 0,DateTime,T,P,U,Ff,Nh,H,VV,sss,...,DD_Wind blowing from the north-west,DD_Wind blowing from the south,DD_Wind blowing from the south-east,DD_Wind blowing from the south-southeast,DD_Wind blowing from the south-southwest,DD_Wind blowing from the south-west,DD_Wind blowing from the west,DD_Wind blowing from the west-northwest,DD_Wind blowing from the west-southwest,DD_variable wind direction
0,0,2012-09-26 08:00,21.0,1013.9,3,NaN,0,NaN,NaN,0.0,...,0,0,0,0,0,0,0,0,1,0
1,1,2012-09-26 09:00,24.0,1013.9,4,NaN,0,NaN,NaN,0.0,...,0,0,0,0,1,0,0,0,0,0
2,2,2012-09-26 10:00,26.0,1013.9,4,NaN,0,NaN,NaN,0.0,...,0,0,0,0,1,0,0,0,0,0
3,3,2012-09-26 11:00,28.0,1013.9,3,NaN,0,NaN,NaN,0.0,...,0,0,0,0,0,1,0,0,0,0
4,4,2012-09-26 12:00,29.0,1013.9,4,NaN,0,NaN,NaN,0.0,...,0,1,0,0,0,0,0,0,0,0

In [33]:
del data2["Unnamed: 0"]

In [34]:
data2.head()

,DateTime,T,P,U,Ff,Nh,H,VV,sss,"DD_Calm, no wind",...,DD_Wind blowing from the north-west,DD_Wind blowing from the south,DD_Wind blowing from the south-east,DD_Wind blowing from the south-southeast,DD_Wind blowing from the south-southwest,DD_Wind blowing from the south-west,DD_Wind blowing from the west,DD_Wind blowing from the west-northwest,DD_Wind blowing from the west-southwest,DD_variable wind direction
0,2012-09-26 08:00,21.0,1013.9,3,NaN,0,NaN,NaN,0.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2012-09-26 09:00,24.0,1013.9,4,NaN,0,NaN,NaN,0.0,0,...,0,0,0,0,1,0,0,0,0,0
2,2012-09-26 10:00,26.0,1013.9,4,NaN,0,NaN,NaN,0.0,0,...,0,0,0,0,1,0,0,0,0,0
3,2012-09-26 11:00,28.0,1013.9,3,NaN,0,NaN,NaN,0.0,0,...,0,0,0,0,0,1,0,0,0,0
4,2012-09-26 12:00,29.0,1013.9,4,NaN,0,NaN,NaN,0.0,0,...,0,1,0,0,0,0,0,0,0,0

In [35]:
data2.to_csv("podaci_one_hot_enkodiranje_DD.csv", index = False)

In [36]:
# nije potrebno civati sve podatke, na neku sirinu
# vise datasetova, imamo vise izvora, meta podatke, koji treba da se dopunjuju
# ne moramo vrsiti predikciju za oba dataset-a u Srbiji, svejedno koji od ta 2
#

In [37]:
data2.isna().sum()

DateTime                                        0
T                                               0
P                                               0
U                                               0
Ff                                          36774
Nh                                              0
H                                           53192
VV                                          41399
sss                                             0
DD_Calm, no wind                                0
DD_Wind blowing from the east                   0
DD_Wind blowing from the east-northeast         0
DD_Wind blowing from the east-southeast         0
DD_Wind blowing from the north                  0
DD_Wind blowing from the north-east             0
DD_Wind blowing from the north-northeast        0
DD_Wind blowing from the north-northwest        0
DD_Wind blowing from the north-west             0
DD_Wind blowing from the south                  0
DD_Wind blowing from the south-east             0
DD_Wind blowing from the south-southeast        0
DD_Wind blowing from the south-southwest        0
DD_Wind blowing from the south-west             0
DD_Wind blowing from the west                   0
DD_Wind blowing from the west-northwest         0
DD_Wind blowing from the west-southwest         0
DD_variable wind direction                      0
dtype: int64